services:
  - type: web
    name: facebook-gpt-comment-bot
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false